application: asksheilla
version: dev
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: static/css

- url: /.*
  script: main.py

libraries:
- name: django
  version: "1.2"
